### ISSUE TITLE
Appears to break pop mark command

### ISSUE THREAD

**Issue by larkery** [paldepind/composable.el#10]
Hello,

When I have `composable-mark-mode` enabled, popping the mark seems to do nothing (i.e. `C-u C-SPC`).

I have tested this with the minimal configuration i.e. `emacs -Q`, `(load "composable-mark.el") (load "composable.el") (composable-mark-mode)` followed by pushing and popping the mark.

Halp!

Thanks,

Tom

**Comment by paldepind** [comment]
Thank you for reporting this issue.

I think I've fixed it. Please try the latest version once it becomes available on MELPA.
