### ISSUE TITLE
Numeric prefixes don't work

### ISSUE THREAD

**Issue by d12frosted** [paldepind/composable.el#11]
Hello,

Just run into problem with numeric prefixes. Tried several commands with them and seem like none of them are working properly. Here is my setup.
1. `$ emacs -Q`
2. add `composable` to `load-path`
3. `(require 'composable)`
4. switch to scratch buffer (in fundamental mode)
5. `(composable-mode)`

So I am performing following steps.
1. type `first second third fourth`
2. place cursor at `f` in `first`
3. `C-w 3 f`

I expect it to kill `first second third` and leave `fourth`. But instead it places `fff`. Note that doing `C-w f C-w f C-w f` works as expected as well as `C-w f f f`. 

Am I missing something? 

P. S. `M-w`, `M-;` commands also insert `f` or `l` or whatever I used as target. 

P. P. S. I am using emacs-25. Will try on emacs 24 a little bit later.

**Comment by paldepind** [comment]
Are you using the latest version? This might be due to #6, a bug in Emacs 25 which was recently fixed.

**Comment by d12frosted** [comment]
I installed the version from MELPA. Let me try with latest git version.

**Comment by d12frosted** [comment]
Yes, you're right. Just tried git version and everything works fine. Sorry for the false alarm :)

**Comment by paldepind** [comment]
I think the latest version should be on MELPA as well?

**Comment by d12frosted** [comment]
Hm, somehow I've installed `20160427.128` instead of `20160501.921`. I actually tried `composable` while I was experiencing some problems with i/c, so might be it.
