### ISSUE TITLE
M-w on a region should just copy instead of waiting for a text object

### ISSUE THREAD

**Issue by tuhdo** [paldepind/composable.el#13]
Currently, `M-w` on an active region does not fall back like `C-w` currently does. I think it's a bug.

**Comment by paldepind** [comment]
I cannot reproduce this. What version of Emacs are you using?

**Comment by paldepind** [comment]
@tuhdo, Hello again. Which version of Emacs are you using? And are you using the latest version of composable.el? Did this work for you previously?
