### ISSUE TITLE
Way to show object binding keys automatically

### ISSUE THREAD

**Issue by itamarst** [paldepind/composable.el#20]
I've gotten used to which-key showing all my options, but that doesn't happen when `compose-object-mode`, and it would be nice to see the various object commands I can use to help memorize them better.

It would be nice if either:

1. composable-object-mode worked with which-key automatically. I.e. I do C-w and now I see menu that tells me what "l" etc. does.
2. Or, there was a hydra provided (or just it's documented how to do a hydra).

**Comment by Ergus** [comment]
Hi Itamarst: 

I know this issue is very old, but just in case I just added a commit (PR) that provides which-key integration. 

I don't know if you still use composable, but just in case it is there any way (and some other minor fixes improvements are pending to acceptance.)

**Comment by paldepind** [comment]
Composable now [integrates with whick-key](https://github.com/paldepind/composable.el#which-key-integration). Thanks a lot @Ergus :tada:

**Comment by itamarst** [comment]
Thanks @Ergus —never ended up using composable, but this makes it more likely I will.
