### ISSUE TITLE
Problem with mark

### ISSUE THREAD

**Issue by Ergus** [paldepind/composable.el#23]
Hi:

When the option `mark-even-if-inactive` is `nil` the package only gives errors because there is not mark.

The solution is to call the `mark` command as `(mark t)` to avoid the error and add a conditional when needed.

**Comment by paldepind** [comment]
Closed by #24.

**Comment by Ergus** [comment]
Hi:
I still have a bug when mark-even-if-inactive is `nil`. Composes like: 
`M-w a` does not work. I am looking around to fix it but I don't find it and debugging is not working.
