### ISSUE TITLE
Composable save region fails if region exists

### ISSUE THREAD

**Issue by kiranandcode** [paldepind/composable.el#31]
When running `M-w` (composable-save-region) when a region has already been delineated using transient mark mode, emacs reports an error:
```
Marker points into wrong buffer: #<marker in no buffer>
```

Version:
    26.2
Steps to reproduce:
    $ emacs -Q
    evaluate (package initalize)
    evaluate (composable-mode 1)
    Select a region using movement while holding shift, then press `M-w` to save the region.

**Comment by Ergus** [comment]
Hi:
The issue has been fixed in a pull request that has been accepted and merged today (with several changes and improvements). Please, test and report any new issue you find.
Thanks for using composable.

**Comment by Ergus** [comment]
Hi: is it working for you now?

**Comment by kiranandcode** [comment]
Hi, just tested it - I don't run into the issue any longer.
Thanks!
