### ISSUE TITLE
Moving to Elpa

### ISSUE THREAD

**Issue by Ergus** [paldepind/composable.el#38]
Hi Simon:

Could we consider to add composable to elpa? The most `complex` part is to contact all the developers who contributed to this package with more than 15 lines of code and ask them to request a copyright assignment from the FSF; but with `git shortlog -sne` I actually see that you are the only other than me. I already have the assignment; could you try to do it please?

Best,
Ergus

**Comment by paldepind** [comment]
Hi Ergus. Sorry for the delayed response.

Having composable on Elpa sounds good to me. I've sent the paperwork to FSF. I'll let you know when things are approved.

I think your work in #37 looks really good. You're obviously more experienced with elisp than me. If you are interested I would be very happy to give you commit access to the repository.

**Comment by paldepind** [comment]
Hi again @Ergus. I just wanted to note that I haven't forgotten about this. I've signed the FSF paperwork myself, but I also need to get someone at the university where I'm a student to sign it, and I'm currently working on that.

**Comment by Ergus** [comment]
> Hi again @Ergus. I just wanted to note that I haven't forgotten about this. I've signed the FSF paperwork myself, but I also need to get someone at the university where I'm a student to sign it, and I'm currently working on that.

Hi @paldepind  any progress on this? Remember that the signature is only needed for people who contributed to more than 15 lines of code or so...

**Comment by Ergus** [comment]
Hi @paldepind 

I am considering to make another package with the similar idea than composable, But with a different implementation approach in order to simplify some things and add it to elpa. ANy help is very welcome... Best, Ergus

**Comment by paldepind** [comment]
Hi @Ergus. That sounds great!

Getting the signatures that FSF requires turned out to be a bit of a hassle, so I didn't proceed with it.

Do you expect your implementation to be backward compatible with composable.el? If so, would you like the MELPA package as well? And/or commit access to this git repo?

If you decide to do the development in a new git repo I'll be happy to link to it in the readme as a successor (assuming that it is at least somewhat backward compatible).

**Comment by Ergus** [comment]
> Hi @Ergus. That sounds great!
> 
> Getting the signatures that FSF requires turned out to be a bit of a hassle, so I didn't proceed with it.
> 
> Do you expect your implementation to be backward compatible with composable.el? If so, would you like the MELPA package as well? And/or commit access to this git repo?
> 
My intention is to give the same (or as similar as possible) final user experience; but with a completely different approach relying totally on internal features (like the internal mark-* set of functions, advises and some hooks). Simpler in code base and simpler for testing. I can't reuse any of the actual composable code basically because if their authors do not do a copyright assignment or a disclaim, then it won't be possible to add it to elpa in the future (it is a common issue that elpa has these sort of requirements... but... well.. can't do anything). I would prefer to keep using composable and do these changes progressively in it, to avoid code/project duplication and add the initial effort code to elpa... but that seems being impossible to handle. Something similar seemed to happen to evil/vile and many other packages...

> If you decide to do the development in a new git repo I'll be happy to link to it in the readme as a successor (assuming that it is at least somewhat backward compatible).

From the user side it will be pretty close... sadly I don't have plenty of time these days. Probably I will sacrifice some customization or features details in order to have a simpler code base; but that will come out when I start touching it. First I need to find a way to add tests without ecukes and similes...

best
