### ISSUE TITLE
Previous identifier is killed when point is at the beginning of current identifier

### ISSUE THREAD

**Issue by tuhdo** [paldepind/composable.el#4]
For example, suppose we have this line:

```
pos = curpos;
```

If point is on the `c` character, `C-w y` kills `pos` instead of `curpos`.

**Comment by paldepind** [comment]
Yes. Definitely a bug. I will take a look at it.

**Comment by paldepind** [comment]
This should be fixed by a3c5829. Please confirm when MELPA has build the latest version :smile:
