### ISSUE TITLE
Repeat command with numeric prefix needs composable-end-argument

### ISSUE THREAD

**Issue by sid-kurias** [paldepind/composable.el#6]
The readme says `C-w 10 l` should delete 10 lines but for me it just inserts 10 l characters. To get repeat to work I have to `C-w . 5 l`. I have to use the '.'  composable-end-argument  in there.

I also tried this with emacs -Q and loading just composable-mode.

I am using emacs version 25.1.50.2

**Comment by paldepind** [comment]
This might be because you are using a new version. If you have an older version will you try it in that? Are you compiling from master?

**Comment by sid-kurias** [comment]
I am not compiling from master. I do not have an older version installed. I will try with that in the next few days.

**Comment by paldepind** [comment]
Ok. I excuse my ignorance. But how does one get a version that is more recent than the latest release without compiling from master?

**Comment by sid-kurias** [comment]
guess replying by email does not work.....

If I remember correctly I think I got it from this answer
Prebuilt Ubuntu Emacs "25.1"

http://emacs.stackexchange.com/questions/12772/prebuilt-ubuntu-emacs-25-1

It does work with 24.4, that means it is an issue with 25.1.

Thanks

**Comment by glucas** [comment]
I'm seeing the same issue on an emacs 25.1 (on Windows, in my case, from http://emacsbinw64.sourceforge.net).

**Comment by paldepind** [comment]
Thank you for confirming this @glucas. I have no idea why this breaks. But I hope to take a look at it quite soon.

**Comment by paldepind** [comment]
It seems that I've found the cause of the problem. Please try the latest version once it gets build on MELPA and let me know if it works.

**Comment by sid-kurias** [comment]
yes I can confirm this now works well with 25.1

thank you

**Comment by paldepind** [comment]
Splendid. Thank you for reporting this.
